export interface AssetInfo {
  name: string;
  path: string;
  category: string;
  subcategory?: string;
  animations?: string[];
  description?: string;
}

export interface AssetPack {
  name: string;
  path: string;
  description: string;
  assets: AssetInfo[];
}

export const ASSET_CATALOG: AssetPack[] = [
  {
    name: "Quaternius Monsters",
    path: "/assets/quaternius-monsters",
    description: "4 animated low-poly monsters perfect for RPG and adventure games",
    assets: [
      {
        name: "Bat",
        path: "/assets/monsters/quaternius/Bat.glb",
        category: "monsters",
        subcategory: "flying",
        animations: ["Bat_Attack", "Bat_Attack2", "Bat_Death", "Bat_Flying", "Bat_Hit"],
        description: "Flying bat creature with attack and flying animations"
      },
      {
        name: "Dragon",
        path: "/assets/monsters/quaternius/Dragon.glb",
        category: "monsters",
        subcategory: "flying",
        animations: ["Dragon_Attack", "Dragon_Attack2", "Dragon_Death", "Dragon_Flying", "Dragon_Hit"],
        description: "Small dragon with flight and combat animations"
      },
      {
        name: "Skeleton",
        path: "/assets/monsters/quaternius/Skeleton.glb",
        category: "monsters",
        subcategory: "undead",
        animations: ["Skeleton_Attack", "Skeleton_Death", "Skeleton_Idle", "Skeleton_Running", "Skeleton_Spawn"],
        description: "Skeleton warrior with attack, idle, and running animations"
      },
      {
        name: "Slime",
        path: "/assets/monsters/quaternius/Slime.glb",
        category: "monsters",
        subcategory: "creature",
        animations: ["Slime_Attack", "Slime_Death", "Slime_Idle", "Slime_Walk"],
        description: "Blob slime creature with basic movement and attack"
      }
    ]
  },
  {
    name: "Men Characters",
    path: "/assets/men-characters",
    description: "8 animated male character models with various outfits and 11 animations each",
    assets: [
      {
        name: "Male Casual",
        path: "/assets/characters/men/Male_Casual.glb",
        category: "characters",
        subcategory: "human",
        animations: ["Man_Clapping", "Man_Death", "Man_Idle", "Man_Jump", "Man_Punch", "Man_Run", "Man_RunningJump", "Man_Sitting", "Man_Standing", "Man_SwordSlash", "Man_Walk"],
        description: "Casual outfit male with full animation set"
      },
      {
        name: "Male Long Sleeve",
        path: "/assets/characters/men/Male_LongSleeve.glb",
        category: "characters",
        subcategory: "human",
        animations: ["Man_Clapping", "Man_Death", "Man_Idle", "Man_Jump", "Man_Punch", "Man_Run", "Man_RunningJump", "Man_Sitting", "Man_Standing", "Man_SwordSlash", "Man_Walk"],
        description: "Long sleeve shirt male with full animation set"
      },
      {
        name: "Male Shirt",
        path: "/assets/characters/men/Male_Shirt.glb",
        category: "characters",
        subcategory: "human",
        animations: ["Man_Clapping", "Man_Death", "Man_Idle", "Man_Jump", "Man_Punch", "Man_Run", "Man_RunningJump", "Man_Sitting", "Man_Standing", "Man_SwordSlash", "Man_Walk"],
        description: "T-shirt male with full animation set"
      },
      {
        name: "Male Suit",
        path: "/assets/characters/men/Male_Suit.glb",
        category: "characters",
        subcategory: "human",
        animations: ["Man_Clapping", "Man_Death", "Man_Idle", "Man_Jump", "Man_Punch", "Man_Run", "Man_RunningJump", "Man_Sitting", "Man_Standing", "Man_SwordSlash", "Man_Walk"],
        description: "Business suit male with full animation set"
      },
      {
        name: "Smooth Male Casual",
        path: "/assets/characters/men/Smooth_Male_Casual.glb",
        category: "characters",
        subcategory: "human",
        animations: ["Man_Clapping", "Man_Death", "Man_Idle", "Man_Jump", "Man_Punch", "Man_Run", "Man_RunningJump", "Man_Sitting", "Man_Standing", "Man_SwordSlash", "Man_Walk"],
        description: "Higher poly casual male with smoother mesh"
      },
      {
        name: "Smooth Male Long Sleeve",
        path: "/assets/characters/men/Smooth_Male_LongSleeve.glb",
        category: "characters",
        subcategory: "human",
        animations: ["Man_Clapping", "Man_Death", "Man_Idle", "Man_Jump", "Man_Punch", "Man_Run", "Man_RunningJump", "Man_Sitting", "Man_Standing", "Man_SwordSlash", "Man_Walk"],
        description: "Higher poly long sleeve male with smoother mesh"
      },
      {
        name: "Smooth Male Shirt",
        path: "/assets/characters/men/Smooth_Male_Shirt.glb",
        category: "characters",
        subcategory: "human",
        animations: ["Man_Clapping", "Man_Death", "Man_Idle", "Man_Jump", "Man_Punch", "Man_Run", "Man_RunningJump", "Man_Sitting", "Man_Standing", "Man_SwordSlash", "Man_Walk"],
        description: "Higher poly shirt male with smoother mesh"
      },
      {
        name: "Smooth Male Suit",
        path: "/assets/characters/men/Smooth_Male_Suit.glb",
        category: "characters",
        subcategory: "human",
        animations: ["Man_Clapping", "Man_Death", "Man_Idle", "Man_Jump", "Man_Punch", "Man_Run", "Man_RunningJump", "Man_Sitting", "Man_Standing", "Man_SwordSlash", "Man_Walk"],
        description: "Higher poly suit male with smoother mesh"
      }
    ]
  },
  {
    name: "Action Adventure Animations",
    path: "/assets/action-adventure-anims",
    description: "22 Mixamo-compatible animations for stealth and action gameplay",
    assets: [
      { name: "Cover to Stand", path: "/assets/animations/action-adventure/cover_to_stand.glb", category: "animations", subcategory: "cover" },
      { name: "Cover to Stand 2", path: "/assets/animations/action-adventure/cover_to_stand__2_.glb", category: "animations", subcategory: "cover" },
      { name: "Crouched Sneaking Left", path: "/assets/animations/action-adventure/crouched_sneaking_left.glb", category: "animations", subcategory: "stealth" },
      { name: "Crouched Sneaking Right", path: "/assets/animations/action-adventure/crouched_sneaking_right.glb", category: "animations", subcategory: "stealth" },
      { name: "Falling Idle", path: "/assets/animations/action-adventure/falling_idle.glb", category: "animations", subcategory: "movement" },
      { name: "Falling to Roll", path: "/assets/animations/action-adventure/falling_to_roll.glb", category: "animations", subcategory: "movement" },
      { name: "Hard Landing", path: "/assets/animations/action-adventure/hard_landing.glb", category: "animations", subcategory: "movement" },
      { name: "Idle", path: "/assets/animations/action-adventure/idle.glb", category: "animations", subcategory: "idle" },
      { name: "Idle 2", path: "/assets/animations/action-adventure/idle__2_.glb", category: "animations", subcategory: "idle" },
      { name: "Idle 3", path: "/assets/animations/action-adventure/idle__3_.glb", category: "animations", subcategory: "idle" },
      { name: "Idle 4", path: "/assets/animations/action-adventure/idle__4_.glb", category: "animations", subcategory: "idle" },
      { name: "Idle 5", path: "/assets/animations/action-adventure/idle__5_.glb", category: "animations", subcategory: "idle" },
      { name: "Jumping Up", path: "/assets/animations/action-adventure/jumping_up.glb", category: "animations", subcategory: "movement" },
      { name: "Left Cover Sneak", path: "/assets/animations/action-adventure/left_cover_sneak.glb", category: "animations", subcategory: "stealth" },
      { name: "Left Turn", path: "/assets/animations/action-adventure/left_turn.glb", category: "animations", subcategory: "movement" },
      { name: "Right Cover Sneak", path: "/assets/animations/action-adventure/right_cover_sneak.glb", category: "animations", subcategory: "stealth" },
      { name: "Right Turn", path: "/assets/animations/action-adventure/right_turn.glb", category: "animations", subcategory: "movement" },
      { name: "Running", path: "/assets/animations/action-adventure/running.glb", category: "animations", subcategory: "movement" },
      { name: "Run to Stop", path: "/assets/animations/action-adventure/run_to_stop.glb", category: "animations", subcategory: "movement" },
      { name: "Stand to Cover", path: "/assets/animations/action-adventure/stand_to_cover.glb", category: "animations", subcategory: "cover" },
      { name: "Stand to Cover 2", path: "/assets/animations/action-adventure/stand_to_cover__2_.glb", category: "animations", subcategory: "cover" },
      { name: "Walking", path: "/assets/animations/action-adventure/walking.glb", category: "animations", subcategory: "movement" }
    ]
  },
  {
    name: "Survival Props",
    path: "/assets/survival-props",
    description: "59 survival game props including tools, weapons, camping gear, and consumables",
    assets: [
      { name: "Animal Hide", path: "/assets/props/survival/Animal_Hide.glb", category: "props", subcategory: "materials" },
      { name: "Arrow", path: "/assets/props/survival/Arrow.glb", category: "props", subcategory: "weapons" },
      { name: "Axe", path: "/assets/props/survival/Axe.glb", category: "props", subcategory: "tools" },
      { name: "Bandage", path: "/assets/props/survival/Bandage.glb", category: "props", subcategory: "medical" },
      { name: "Basket", path: "/assets/props/survival/Basket.glb", category: "props", subcategory: "containers" },
      { name: "Battery", path: "/assets/props/survival/Battery.glb", category: "props", subcategory: "electronics" },
      { name: "Bear Trap", path: "/assets/props/survival/Bear_Trap.glb", category: "props", subcategory: "traps" },
      { name: "Blankets", path: "/assets/props/survival/Blankets.glb", category: "props", subcategory: "camping" },
      { name: "Boots", path: "/assets/props/survival/Boots.glb", category: "props", subcategory: "clothing" },
      { name: "Bow", path: "/assets/props/survival/Bow.glb", category: "props", subcategory: "weapons" },
      { name: "Bucket", path: "/assets/props/survival/Bucket.glb", category: "props", subcategory: "containers" },
      { name: "Clay Jug", path: "/assets/props/survival/Clay_Jug.glb", category: "props", subcategory: "containers" },
      { name: "Coin Pouch", path: "/assets/props/survival/Coin_Pouch.glb", category: "props", subcategory: "containers" },
      { name: "Compass", path: "/assets/props/survival/Compass.glb", category: "props", subcategory: "navigation" },
      { name: "Desert Shelter", path: "/assets/props/survival/Desert_shelter.glb", category: "props", subcategory: "structures" },
      { name: "Fire", path: "/assets/props/survival/Fire.glb", category: "props", subcategory: "effects" },
      { name: "First Aid Kit", path: "/assets/props/survival/First_Aid_Kit.glb", category: "props", subcategory: "medical" },
      { name: "Fishing Rod", path: "/assets/props/survival/Fishing_Rod.glb", category: "props", subcategory: "tools" },
      { name: "Flashlight", path: "/assets/props/survival/Flashlight.glb", category: "props", subcategory: "electronics" },
      { name: "Food", path: "/assets/props/survival/Food.glb", category: "props", subcategory: "consumables" },
      { name: "Frying Pan", path: "/assets/props/survival/Frying_Pan.glb", category: "props", subcategory: "cooking" },
      { name: "Gas Mask", path: "/assets/props/survival/gas_mask.glb", category: "props", subcategory: "clothing" },
      { name: "Generator", path: "/assets/props/survival/Generator.glb", category: "props", subcategory: "electronics" },
      { name: "Glue", path: "/assets/props/survival/Glue.glb", category: "props", subcategory: "materials" },
      { name: "Hammer", path: "/assets/props/survival/Hammer.glb", category: "props", subcategory: "tools" },
      { name: "Hammock", path: "/assets/props/survival/Hammock.glb", category: "props", subcategory: "camping" },
      { name: "Hatchet", path: "/assets/props/survival/Hatchet.glb", category: "props", subcategory: "tools" },
      { name: "Knife", path: "/assets/props/survival/Knife.glb", category: "props", subcategory: "weapons" },
      { name: "Lantern", path: "/assets/props/survival/Lantern.glb", category: "props", subcategory: "lighting" },
      { name: "Lure", path: "/assets/props/survival/Lure.glb", category: "props", subcategory: "tools" },
      { name: "Map", path: "/assets/props/survival/Map.glb", category: "props", subcategory: "navigation" },
      { name: "Matchstick", path: "/assets/props/survival/Matchstick.glb", category: "props", subcategory: "tools" },
      { name: "Mushroom", path: "/assets/props/survival/Mushroom.glb", category: "props", subcategory: "consumables" },
      { name: "Nail", path: "/assets/props/survival/Nail.glb", category: "props", subcategory: "materials" },
      { name: "Notebook", path: "/assets/props/survival/Notebook.glb", category: "props", subcategory: "tools" },
      { name: "Padlock", path: "/assets/props/survival/Padlock.glb", category: "props", subcategory: "tools" },
      { name: "Pickaxe", path: "/assets/props/survival/Pickaxe.glb", category: "props", subcategory: "tools" },
      { name: "Pot", path: "/assets/props/survival/Pot.glb", category: "props", subcategory: "cooking" },
      { name: "Raspberry", path: "/assets/props/survival/Raspberry.glb", category: "props", subcategory: "consumables" },
      { name: "Red Cooler", path: "/assets/props/survival/Red_Cooler_Open_with_Beer.glb", category: "props", subcategory: "containers" },
      { name: "Resin Table", path: "/assets/props/survival/Resin_Table.glb", category: "props", subcategory: "furniture" },
      { name: "Rope", path: "/assets/props/survival/Rope.glb", category: "props", subcategory: "materials" },
      { name: "Saw", path: "/assets/props/survival/Saw.glb", category: "props", subcategory: "tools" },
      { name: "Seed", path: "/assets/props/survival/Seed.glb", category: "props", subcategory: "materials" },
      { name: "Shovel", path: "/assets/props/survival/Shovel.glb", category: "props", subcategory: "tools" },
      { name: "Smoke", path: "/assets/props/survival/Smoke.glb", category: "props", subcategory: "effects" },
      { name: "Snack Bar", path: "/assets/props/survival/Snack_Bar.glb", category: "props", subcategory: "consumables" },
      { name: "Spear", path: "/assets/props/survival/Spear.glb", category: "props", subcategory: "weapons" },
      { name: "Stone", path: "/assets/props/survival/Stone.glb", category: "props", subcategory: "materials" },
      { name: "Tablet", path: "/assets/props/survival/Tablet.glb", category: "props", subcategory: "electronics" },
      { name: "Tent", path: "/assets/props/survival/Tent.glb", category: "props", subcategory: "camping" },
      { name: "Towel", path: "/assets/props/survival/Towel.glb", category: "props", subcategory: "camping" },
      { name: "Trapdoor", path: "/assets/props/survival/Trapdoor.glb", category: "props", subcategory: "structures" },
      { name: "Tree Roots", path: "/assets/props/survival/Tree_roots.glb", category: "props", subcategory: "nature" },
      { name: "Twine", path: "/assets/props/survival/Twine_2.glb", category: "props", subcategory: "materials" },
      { name: "Vine", path: "/assets/props/survival/Vine.glb", category: "props", subcategory: "nature" },
      { name: "Water Bottle", path: "/assets/props/survival/Water_bottle.glb", category: "props", subcategory: "consumables" },
      { name: "Whistle", path: "/assets/props/survival/Whistle.glb", category: "props", subcategory: "tools" },
      { name: "Wood", path: "/assets/props/survival/Wood.glb", category: "props", subcategory: "materials" }
    ]
  },
  {
    name: "Kenney Prototype Kit",
    path: "/assets/kenney-prototype",
    description: "145 prototyping assets including shapes, walls, floors, stairs, doors, pipes, vehicles, and targets for level design",
    assets: [
      { name: "Animal Bison", path: "/assets/structures/prototype/animal-bison.glb", category: "characters", subcategory: "animals", description: "Prototype bison animal figure" },
      { name: "Animal Dog", path: "/assets/structures/prototype/animal-dog.glb", category: "characters", subcategory: "animals", description: "Prototype dog animal figure" },
      { name: "Animal Horse", path: "/assets/structures/prototype/animal-horse.glb", category: "characters", subcategory: "animals", description: "Prototype horse animal figure" },
      { name: "Button Floor Round", path: "/assets/structures/prototype/button-floor-round.glb", category: "props", subcategory: "markers", description: "Round floor button trigger" },
      { name: "Button Floor Round Small", path: "/assets/structures/prototype/button-floor-round-small.glb", category: "props", subcategory: "markers", description: "Small round floor button trigger" },
      { name: "Button Floor Square", path: "/assets/structures/prototype/button-floor-square.glb", category: "props", subcategory: "markers", description: "Square floor button trigger" },
      { name: "Button Floor Square Small", path: "/assets/structures/prototype/button-floor-square-small.glb", category: "props", subcategory: "markers", description: "Small square floor button trigger" },
      { name: "Coin", path: "/assets/structures/prototype/coin.glb", category: "props", subcategory: "markers", description: "Collectible coin pickup" },
      { name: "Column", path: "/assets/structures/prototype/column.glb", category: "structures", subcategory: "support", description: "Standard support column" },
      { name: "Column Low", path: "/assets/structures/prototype/column-low.glb", category: "structures", subcategory: "support", description: "Low height support column" },
      { name: "Column Rounded", path: "/assets/structures/prototype/column-rounded.glb", category: "structures", subcategory: "support", description: "Rounded support column" },
      { name: "Column Rounded Low", path: "/assets/structures/prototype/column-rounded-low.glb", category: "structures", subcategory: "support", description: "Low rounded support column" },
      { name: "Column Triangle", path: "/assets/structures/prototype/column-triangle.glb", category: "structures", subcategory: "support", description: "Triangular support column" },
      { name: "Column Triangle Low", path: "/assets/structures/prototype/column-triangle-low.glb", category: "structures", subcategory: "support", description: "Low triangular support column" },
      { name: "Crate", path: "/assets/structures/prototype/crate.glb", category: "props", subcategory: "containers", description: "Standard prototype crate" },
      { name: "Crate Color", path: "/assets/structures/prototype/crate-color.glb", category: "props", subcategory: "containers", description: "Colored prototype crate" },
      { name: "Door Garage", path: "/assets/structures/prototype/door-garage.glb", category: "structures", subcategory: "doors", description: "Garage-style roll-up door" },
      { name: "Door Rotate", path: "/assets/structures/prototype/door-rotate.glb", category: "structures", subcategory: "doors", description: "Rotating hinged door" },
      { name: "Door Sliding", path: "/assets/structures/prototype/door-sliding.glb", category: "structures", subcategory: "doors", description: "Single sliding door" },
      { name: "Door Sliding Double", path: "/assets/structures/prototype/door-sliding-double.glb", category: "structures", subcategory: "doors", description: "Double sliding door" },
      { name: "Door Sliding Double Round", path: "/assets/structures/prototype/door-sliding-double-round.glb", category: "structures", subcategory: "doors", description: "Double sliding door with round frame" },
      { name: "Door Sliding Double Wide", path: "/assets/structures/prototype/door-sliding-double-wide.glb", category: "structures", subcategory: "doors", description: "Wide double sliding door" },
      { name: "Figurine", path: "/assets/structures/prototype/figurine.glb", category: "characters", subcategory: "npcs", description: "Basic humanoid figurine" },
      { name: "Figurine Cube", path: "/assets/structures/prototype/figurine-cube.glb", category: "characters", subcategory: "npcs", description: "Cube-shaped figurine" },
      { name: "Figurine Cube Detailed", path: "/assets/structures/prototype/figurine-cube-detailed.glb", category: "characters", subcategory: "npcs", description: "Detailed cube-shaped figurine" },
      { name: "Figurine Large", path: "/assets/structures/prototype/figurine-large.glb", category: "characters", subcategory: "npcs", description: "Large humanoid figurine" },
      { name: "Flag", path: "/assets/structures/prototype/flag.glb", category: "props", subcategory: "decorations", description: "Flag on a pole" },
      { name: "Floor Diagonal", path: "/assets/structures/prototype/floor-diagonal.glb", category: "structures", subcategory: "floors", description: "Diagonal floor tile" },
      { name: "Floor Small Diagonal", path: "/assets/structures/prototype/floor-small-diagonal.glb", category: "structures", subcategory: "floors", description: "Small diagonal floor tile" },
      { name: "Floor Small Square", path: "/assets/structures/prototype/floor-small-square.glb", category: "structures", subcategory: "floors", description: "Small square floor tile" },
      { name: "Floor Square", path: "/assets/structures/prototype/floor-square.glb", category: "structures", subcategory: "floors", description: "Standard square floor tile" },
      { name: "Floor Thick", path: "/assets/structures/prototype/floor-thick.glb", category: "structures", subcategory: "floors", description: "Thick floor platform" },
      { name: "Floor Thick Corner Diagonal", path: "/assets/structures/prototype/floor-thick-corner-diagonal.glb", category: "structures", subcategory: "floors", description: "Thick floor diagonal corner piece" },
      { name: "Floor Thick Corner Round", path: "/assets/structures/prototype/floor-thick-corner-round.glb", category: "structures", subcategory: "floors", description: "Thick floor round corner piece" },
      { name: "Floor Thick Corner Rounded", path: "/assets/structures/prototype/floor-thick-corner-rounded.glb", category: "structures", subcategory: "floors", description: "Thick floor rounded corner piece" },
      { name: "Hat Cap", path: "/assets/structures/prototype/hat-cap.glb", category: "props", subcategory: "clothing", description: "Baseball-style cap" },
      { name: "Hat Hard", path: "/assets/structures/prototype/hat-hard.glb", category: "props", subcategory: "clothing", description: "Construction hard hat" },
      { name: "Indicator Doorway", path: "/assets/structures/prototype/indicator-doorway.glb", category: "props", subcategory: "markers", description: "Doorway position indicator" },
      { name: "Indicator Round A", path: "/assets/structures/prototype/indicator-round-a.glb", category: "props", subcategory: "markers", description: "Round indicator variant A" },
      { name: "Indicator Round B", path: "/assets/structures/prototype/indicator-round-b.glb", category: "props", subcategory: "markers", description: "Round indicator variant B" },
      { name: "Indicator Round C", path: "/assets/structures/prototype/indicator-round-c.glb", category: "props", subcategory: "markers", description: "Round indicator variant C" },
      { name: "Indicator Round D", path: "/assets/structures/prototype/indicator-round-d.glb", category: "props", subcategory: "markers", description: "Round indicator variant D" },
      { name: "Indicator Round E", path: "/assets/structures/prototype/indicator-round-e.glb", category: "props", subcategory: "markers", description: "Round indicator variant E" },
      { name: "Indicator Round F", path: "/assets/structures/prototype/indicator-round-f.glb", category: "props", subcategory: "markers", description: "Round indicator variant F" },
      { name: "Indicator Special Area", path: "/assets/structures/prototype/indicator-special-area.glb", category: "props", subcategory: "markers", description: "Special area indicator marker" },
      { name: "Indicator Special Arrow", path: "/assets/structures/prototype/indicator-special-arrow.glb", category: "props", subcategory: "markers", description: "Arrow direction indicator" },
      { name: "Indicator Special Cross", path: "/assets/structures/prototype/indicator-special-cross.glb", category: "props", subcategory: "markers", description: "Cross-shaped indicator marker" },
      { name: "Indicator Special Lines", path: "/assets/structures/prototype/indicator-special-lines.glb", category: "props", subcategory: "markers", description: "Lines pattern indicator marker" },
      { name: "Indicator Square A", path: "/assets/structures/prototype/indicator-square-a.glb", category: "props", subcategory: "markers", description: "Square indicator variant A" },
      { name: "Indicator Square B", path: "/assets/structures/prototype/indicator-square-b.glb", category: "props", subcategory: "markers", description: "Square indicator variant B" },
      { name: "Indicator Square C", path: "/assets/structures/prototype/indicator-square-c.glb", category: "props", subcategory: "markers", description: "Square indicator variant C" },
      { name: "Indicator Square D", path: "/assets/structures/prototype/indicator-square-d.glb", category: "props", subcategory: "markers", description: "Square indicator variant D" },
      { name: "Indicator Square E", path: "/assets/structures/prototype/indicator-square-e.glb", category: "props", subcategory: "markers", description: "Square indicator variant E" },
      { name: "Indicator Square F", path: "/assets/structures/prototype/indicator-square-f.glb", category: "props", subcategory: "markers", description: "Square indicator variant F" },
      { name: "Ladder", path: "/assets/structures/prototype/ladder.glb", category: "structures", subcategory: "traversal", description: "Standard climbing ladder" },
      { name: "Ladder Color", path: "/assets/structures/prototype/ladder-color.glb", category: "structures", subcategory: "traversal", description: "Colored climbing ladder" },
      { name: "Ladder Top", path: "/assets/structures/prototype/ladder-top.glb", category: "structures", subcategory: "traversal", description: "Ladder top section with platform" },
      { name: "Lever Double", path: "/assets/structures/prototype/lever-double.glb", category: "props", subcategory: "interactive", description: "Double-action lever switch" },
      { name: "Lever Single", path: "/assets/structures/prototype/lever-single.glb", category: "props", subcategory: "interactive", description: "Single-action lever switch" },
      { name: "Number 0", path: "/assets/structures/prototype/number-0.glb", category: "props", subcategory: "markers", description: "Number 0 marker" },
      { name: "Number 1", path: "/assets/structures/prototype/number-1.glb", category: "props", subcategory: "markers", description: "Number 1 marker" },
      { name: "Number 2", path: "/assets/structures/prototype/number-2.glb", category: "props", subcategory: "markers", description: "Number 2 marker" },
      { name: "Number 3", path: "/assets/structures/prototype/number-3.glb", category: "props", subcategory: "markers", description: "Number 3 marker" },
      { name: "Number 4", path: "/assets/structures/prototype/number-4.glb", category: "props", subcategory: "markers", description: "Number 4 marker" },
      { name: "Number 5", path: "/assets/structures/prototype/number-5.glb", category: "props", subcategory: "markers", description: "Number 5 marker" },
      { name: "Number 6", path: "/assets/structures/prototype/number-6.glb", category: "props", subcategory: "markers", description: "Number 6 marker" },
      { name: "Number 7", path: "/assets/structures/prototype/number-7.glb", category: "props", subcategory: "markers", description: "Number 7 marker" },
      { name: "Number 8", path: "/assets/structures/prototype/number-8.glb", category: "props", subcategory: "markers", description: "Number 8 marker" },
      { name: "Number 9", path: "/assets/structures/prototype/number-9.glb", category: "props", subcategory: "markers", description: "Number 9 marker" },
      { name: "Number Double 0", path: "/assets/structures/prototype/number-double-0.glb", category: "props", subcategory: "markers", description: "Double digit 00 marker" },
      { name: "Number Double 1", path: "/assets/structures/prototype/number-double-1.glb", category: "props", subcategory: "markers", description: "Double digit 01 marker" },
      { name: "Number Double 2", path: "/assets/structures/prototype/number-double-2.glb", category: "props", subcategory: "markers", description: "Double digit 02 marker" },
      { name: "Number Double 3", path: "/assets/structures/prototype/number-double-3.glb", category: "props", subcategory: "markers", description: "Double digit 03 marker" },
      { name: "Number Double 4", path: "/assets/structures/prototype/number-double-4.glb", category: "props", subcategory: "markers", description: "Double digit 04 marker" },
      { name: "Number Double 5", path: "/assets/structures/prototype/number-double-5.glb", category: "props", subcategory: "markers", description: "Double digit 05 marker" },
      { name: "Number Double 6", path: "/assets/structures/prototype/number-double-6.glb", category: "props", subcategory: "markers", description: "Double digit 06 marker" },
      { name: "Number Double 7", path: "/assets/structures/prototype/number-double-7.glb", category: "props", subcategory: "markers", description: "Double digit 07 marker" },
      { name: "Number Double 8", path: "/assets/structures/prototype/number-double-8.glb", category: "props", subcategory: "markers", description: "Double digit 08 marker" },
      { name: "Number Double 9", path: "/assets/structures/prototype/number-double-9.glb", category: "props", subcategory: "markers", description: "Double digit 09 marker" },
      { name: "Pipe", path: "/assets/structures/prototype/pipe.glb", category: "structures", subcategory: "support", description: "Straight pipe section" },
      { name: "Pipe Corner", path: "/assets/structures/prototype/pipe-corner.glb", category: "structures", subcategory: "support", description: "Corner pipe connector" },
      { name: "Pipe Half", path: "/assets/structures/prototype/pipe-half.glb", category: "structures", subcategory: "support", description: "Half-length pipe section" },
      { name: "Pipe Half Section", path: "/assets/structures/prototype/pipe-half-section.glb", category: "structures", subcategory: "support", description: "Half pipe cross-section" },
      { name: "Pipe Section", path: "/assets/structures/prototype/pipe-section.glb", category: "structures", subcategory: "support", description: "Pipe cross-section piece" },
      { name: "Pipe Split", path: "/assets/structures/prototype/pipe-split.glb", category: "structures", subcategory: "support", description: "Pipe T-junction splitter" },
      { name: "Shape Cube", path: "/assets/structures/prototype/shape-cube.glb", category: "structures", subcategory: "primitives", description: "Basic cube primitive" },
      { name: "Shape Cube Half", path: "/assets/structures/prototype/shape-cube-half.glb", category: "structures", subcategory: "primitives", description: "Half-height cube primitive" },
      { name: "Shape Cube Rounded", path: "/assets/structures/prototype/shape-cube-rounded.glb", category: "structures", subcategory: "primitives", description: "Rounded cube primitive" },
      { name: "Shape Cylinder", path: "/assets/structures/prototype/shape-cylinder.glb", category: "structures", subcategory: "primitives", description: "Basic cylinder primitive" },
      { name: "Shape Cylinder Detailed", path: "/assets/structures/prototype/shape-cylinder-detailed.glb", category: "structures", subcategory: "primitives", description: "High-detail cylinder primitive" },
      { name: "Shape Cylinder Half", path: "/assets/structures/prototype/shape-cylinder-half.glb", category: "structures", subcategory: "primitives", description: "Half cylinder primitive" },
      { name: "Shape Cylinder Half Detailed", path: "/assets/structures/prototype/shape-cylinder-half-detailed.glb", category: "structures", subcategory: "primitives", description: "Detailed half cylinder primitive" },
      { name: "Shape Hexagon", path: "/assets/structures/prototype/shape-hexagon.glb", category: "structures", subcategory: "primitives", description: "Hexagonal prism primitive" },
      { name: "Shape Hexagon Half", path: "/assets/structures/prototype/shape-hexagon-half.glb", category: "structures", subcategory: "primitives", description: "Half hexagonal prism primitive" },
      { name: "Shape Hollow Cylinder", path: "/assets/structures/prototype/shape-hollow-cylinder.glb", category: "structures", subcategory: "primitives", description: "Hollow cylinder primitive" },
      { name: "Shape Hollow Cylinder Detailed", path: "/assets/structures/prototype/shape-hollow-cylinder-detailed.glb", category: "structures", subcategory: "primitives", description: "Detailed hollow cylinder primitive" },
      { name: "Shape Hollow Cylinder Half", path: "/assets/structures/prototype/shape-hollow-cylinder-half.glb", category: "structures", subcategory: "primitives", description: "Half hollow cylinder primitive" },
      { name: "Shape Hollow Cylinder Half Detailed", path: "/assets/structures/prototype/shape-hollow-cylinder-half-detailed.glb", category: "structures", subcategory: "primitives", description: "Detailed half hollow cylinder" },
      { name: "Shape Hollow Hexagon", path: "/assets/structures/prototype/shape-hollow-hexagon.glb", category: "structures", subcategory: "primitives", description: "Hollow hexagonal prism primitive" },
      { name: "Shape Hollow Hexagon Half", path: "/assets/structures/prototype/shape-hollow-hexagon-half.glb", category: "structures", subcategory: "primitives", description: "Half hollow hexagonal prism" },
      { name: "Shape Slope", path: "/assets/structures/prototype/shape-slope.glb", category: "structures", subcategory: "primitives", description: "Slope ramp primitive" },
      { name: "Shape Triangular Prism", path: "/assets/structures/prototype/shape-triangular-prism.glb", category: "structures", subcategory: "primitives", description: "Triangular prism primitive" },
      { name: "Shape Triangular Prism Low", path: "/assets/structures/prototype/shape-triangular-prism-low.glb", category: "structures", subcategory: "primitives", description: "Low triangular prism primitive" },
      { name: "Stairs", path: "/assets/structures/prototype/stairs.glb", category: "structures", subcategory: "traversal", description: "Standard staircase" },
      { name: "Stairs Diagonal", path: "/assets/structures/prototype/stairs-diagonal.glb", category: "structures", subcategory: "traversal", description: "Diagonal staircase" },
      { name: "Stairs Diagonal Narrow", path: "/assets/structures/prototype/stairs-diagonal-narrow.glb", category: "structures", subcategory: "traversal", description: "Narrow diagonal staircase" },
      { name: "Stairs Diagonal Small", path: "/assets/structures/prototype/stairs-diagonal-small.glb", category: "structures", subcategory: "traversal", description: "Small diagonal staircase" },
      { name: "Stairs Diagonal Small Narrow", path: "/assets/structures/prototype/stairs-diagonal-small-narrow.glb", category: "structures", subcategory: "traversal", description: "Small narrow diagonal staircase" },
      { name: "Stairs Narrow", path: "/assets/structures/prototype/stairs-narrow.glb", category: "structures", subcategory: "traversal", description: "Narrow staircase" },
      { name: "Stairs Small", path: "/assets/structures/prototype/stairs-small.glb", category: "structures", subcategory: "traversal", description: "Small staircase" },
      { name: "Stairs Small Narrow", path: "/assets/structures/prototype/stairs-small-narrow.glb", category: "structures", subcategory: "traversal", description: "Small narrow staircase" },
      { name: "Target A Round", path: "/assets/structures/prototype/target-a-round.glb", category: "props", subcategory: "markers", description: "Round target variant A" },
      { name: "Target A Square", path: "/assets/structures/prototype/target-a-square.glb", category: "props", subcategory: "markers", description: "Square target variant A" },
      { name: "Target B Round", path: "/assets/structures/prototype/target-b-round.glb", category: "props", subcategory: "markers", description: "Round target variant B" },
      { name: "Target B Square", path: "/assets/structures/prototype/target-b-square.glb", category: "props", subcategory: "markers", description: "Square target variant B" },
      { name: "Vehicle", path: "/assets/structures/prototype/vehicle.glb", category: "vehicles", subcategory: "ground", description: "Standard prototype vehicle" },
      { name: "Vehicle Convertible", path: "/assets/structures/prototype/vehicle-convertible.glb", category: "vehicles", subcategory: "ground", description: "Convertible prototype vehicle" },
      { name: "Wall", path: "/assets/structures/prototype/wall.glb", category: "structures", subcategory: "walls", description: "Standard wall segment" },
      { name: "Wall Corner", path: "/assets/structures/prototype/wall-corner.glb", category: "structures", subcategory: "walls", description: "Wall corner piece" },
      { name: "Wall Corner Low", path: "/assets/structures/prototype/wall-corner-low.glb", category: "structures", subcategory: "walls", description: "Low wall corner piece" },
      { name: "Wall Corner Rounded", path: "/assets/structures/prototype/wall-corner-rounded.glb", category: "structures", subcategory: "walls", description: "Rounded wall corner piece" },
      { name: "Wall Corner Rounded Low", path: "/assets/structures/prototype/wall-corner-rounded-low.glb", category: "structures", subcategory: "walls", description: "Low rounded wall corner piece" },
      { name: "Wall Diagonal", path: "/assets/structures/prototype/wall-diagonal.glb", category: "structures", subcategory: "walls", description: "Diagonal wall segment" },
      { name: "Wall Diagonal Low", path: "/assets/structures/prototype/wall-diagonal-low.glb", category: "structures", subcategory: "walls", description: "Low diagonal wall segment" },
      { name: "Wall Doorway", path: "/assets/structures/prototype/wall-doorway.glb", category: "structures", subcategory: "walls", description: "Wall with doorway opening" },
      { name: "Wall Doorway Garage", path: "/assets/structures/prototype/wall-doorway-garage.glb", category: "structures", subcategory: "walls", description: "Wall with garage doorway" },
      { name: "Wall Doorway Round", path: "/assets/structures/prototype/wall-doorway-round.glb", category: "structures", subcategory: "walls", description: "Wall with rounded doorway" },
      { name: "Wall Doorway Sliding", path: "/assets/structures/prototype/wall-doorway-sliding.glb", category: "structures", subcategory: "walls", description: "Wall with sliding door opening" },
      { name: "Wall Doorway Wide", path: "/assets/structures/prototype/wall-doorway-wide.glb", category: "structures", subcategory: "walls", description: "Wall with wide doorway" },
      { name: "Wall Doorway Wide Sliding", path: "/assets/structures/prototype/wall-doorway-wide-sliding.glb", category: "structures", subcategory: "walls", description: "Wall with wide sliding door opening" },
      { name: "Wall Low", path: "/assets/structures/prototype/wall-low.glb", category: "structures", subcategory: "walls", description: "Low height wall segment" },
      { name: "Wall Round", path: "/assets/structures/prototype/wall-round.glb", category: "structures", subcategory: "walls", description: "Rounded wall segment" },
      { name: "Wall Round Low", path: "/assets/structures/prototype/wall-round-low.glb", category: "structures", subcategory: "walls", description: "Low rounded wall segment" },
      { name: "Wall Window Barred Large", path: "/assets/structures/prototype/wall-window-barred-large.glb", category: "structures", subcategory: "walls", description: "Wall with large barred window" },
      { name: "Wall Window Barred Medium", path: "/assets/structures/prototype/wall-window-barred-medium.glb", category: "structures", subcategory: "walls", description: "Wall with medium barred window" },
      { name: "Wall Window Barred Small", path: "/assets/structures/prototype/wall-window-barred-small.glb", category: "structures", subcategory: "walls", description: "Wall with small barred window" },
      { name: "Wall Window Cutout Large", path: "/assets/structures/prototype/wall-window-cutout-large.glb", category: "structures", subcategory: "walls", description: "Wall with large window cutout" },
      { name: "Wall Window Cutout Medium", path: "/assets/structures/prototype/wall-window-cutout-medium.glb", category: "structures", subcategory: "walls", description: "Wall with medium window cutout" },
      { name: "Wall Window Cutout Small", path: "/assets/structures/prototype/wall-window-cutout-small.glb", category: "structures", subcategory: "walls", description: "Wall with small window cutout" },
      { name: "Wall Window Large", path: "/assets/structures/prototype/wall-window-large.glb", category: "structures", subcategory: "walls", description: "Wall with large window" },
      { name: "Wall Window Medium", path: "/assets/structures/prototype/wall-window-medium.glb", category: "structures", subcategory: "walls", description: "Wall with medium window" },
      { name: "Wall Window Small", path: "/assets/structures/prototype/wall-window-small.glb", category: "structures", subcategory: "walls", description: "Wall with small window" },
      { name: "Weapon Shield", path: "/assets/structures/prototype/weapon-shield.glb", category: "weapons", subcategory: "melee", description: "Prototype shield" },
      { name: "Weapon Sword", path: "/assets/structures/prototype/weapon-sword.glb", category: "weapons", subcategory: "melee", description: "Prototype sword" },
      { name: "Wheelchair", path: "/assets/structures/prototype/wheelchair.glb", category: "vehicles", subcategory: "ground", description: "Wheelchair mobility vehicle" }
    ]
  },
  {
    name: "Kenney Medieval Kit",
    path: "/assets/kenney-medieval",
    description: "105 medieval buildings, fortifications, towers, walls, and decorations for castle and village scenes",
    assets: [
      { name: "Barrels", path: "/assets/structures/medieval/barrels.glb", category: "props", subcategory: "containers", description: "Group of wooden barrels" },
      { name: "Battlement", path: "/assets/structures/medieval/battlement.glb", category: "structures", subcategory: "fortifications", description: "Castle battlement wall section" },
      { name: "Battlement Corner Inner", path: "/assets/structures/medieval/battlement-corner-inner.glb", category: "structures", subcategory: "fortifications", description: "Inner corner battlement piece" },
      { name: "Battlement Corner Outer", path: "/assets/structures/medieval/battlement-corner-outer.glb", category: "structures", subcategory: "fortifications", description: "Outer corner battlement piece" },
      { name: "Battlement Half", path: "/assets/structures/medieval/battlement-half.glb", category: "structures", subcategory: "fortifications", description: "Half-length battlement section" },
      { name: "Bricks", path: "/assets/structures/medieval/bricks.glb", category: "props", subcategory: "materials", description: "Stack of stone bricks" },
      { name: "Column", path: "/assets/structures/medieval/column.glb", category: "structures", subcategory: "support", description: "Medieval stone column" },
      { name: "Column Damaged", path: "/assets/structures/medieval/column-damaged.glb", category: "structures", subcategory: "support", description: "Damaged stone column" },
      { name: "Column Paint", path: "/assets/structures/medieval/column-paint.glb", category: "structures", subcategory: "support", description: "Painted stone column" },
      { name: "Column Paint Damaged", path: "/assets/structures/medieval/column-paint-damaged.glb", category: "structures", subcategory: "support", description: "Damaged painted column" },
      { name: "Column Wood", path: "/assets/structures/medieval/column-wood.glb", category: "structures", subcategory: "support", description: "Wooden support column" },
      { name: "Detail Barrel", path: "/assets/structures/medieval/detail-barrel.glb", category: "props", subcategory: "containers", description: "Single decorative barrel" },
      { name: "Detail Crate", path: "/assets/structures/medieval/detail-crate.glb", category: "props", subcategory: "containers", description: "Wooden storage crate" },
      { name: "Detail Crate Ropes", path: "/assets/structures/medieval/detail-crate-ropes.glb", category: "props", subcategory: "containers", description: "Crate secured with ropes" },
      { name: "Detail Crate Small", path: "/assets/structures/medieval/detail-crate-small.glb", category: "props", subcategory: "containers", description: "Small wooden crate" },
      { name: "Dock Corner", path: "/assets/structures/medieval/dock-corner.glb", category: "structures", subcategory: "platforms", description: "Wooden dock corner piece" },
      { name: "Dock Side", path: "/assets/structures/medieval/dock-side.glb", category: "structures", subcategory: "platforms", description: "Wooden dock side section" },
      { name: "Fence", path: "/assets/structures/medieval/fence.glb", category: "structures", subcategory: "walls", description: "Medieval stone fence" },
      { name: "Fence Top", path: "/assets/structures/medieval/fence-top.glb", category: "structures", subcategory: "walls", description: "Fence top railing piece" },
      { name: "Fence Wood", path: "/assets/structures/medieval/fence-wood.glb", category: "structures", subcategory: "walls", description: "Wooden fence section" },
      { name: "Floor", path: "/assets/structures/medieval/floor.glb", category: "structures", subcategory: "floors", description: "Medieval stone floor tile" },
      { name: "Floor Flat", path: "/assets/structures/medieval/floor-flat.glb", category: "structures", subcategory: "floors", description: "Flat stone floor tile" },
      { name: "Floor Stairs", path: "/assets/structures/medieval/floor-stairs.glb", category: "structures", subcategory: "floors", description: "Floor with integrated stairs" },
      { name: "Floor Stairs Corner Inner", path: "/assets/structures/medieval/floor-stairs-corner-inner.glb", category: "structures", subcategory: "floors", description: "Inner corner floor with stairs" },
      { name: "Floor Stairs Corner Outer", path: "/assets/structures/medieval/floor-stairs-corner-outer.glb", category: "structures", subcategory: "floors", description: "Outer corner floor with stairs" },
      { name: "Floor Steps", path: "/assets/structures/medieval/floor-steps.glb", category: "structures", subcategory: "floors", description: "Floor with step edges" },
      { name: "Floor Steps Corner Inner", path: "/assets/structures/medieval/floor-steps-corner-inner.glb", category: "structures", subcategory: "floors", description: "Inner corner floor with steps" },
      { name: "Floor Steps Corner Outer", path: "/assets/structures/medieval/floor-steps-corner-outer.glb", category: "structures", subcategory: "floors", description: "Outer corner floor with steps" },
      { name: "Ladder", path: "/assets/structures/medieval/ladder.glb", category: "structures", subcategory: "traversal", description: "Wooden climbing ladder" },
      { name: "Overhang", path: "/assets/structures/medieval/overhang.glb", category: "structures", subcategory: "roofs", description: "Building overhang section" },
      { name: "Overhang Fence", path: "/assets/structures/medieval/overhang-fence.glb", category: "structures", subcategory: "roofs", description: "Overhang with fence railing" },
      { name: "Overhang Round", path: "/assets/structures/medieval/overhang-round.glb", category: "structures", subcategory: "roofs", description: "Rounded overhang section" },
      { name: "Overhang Round Railing", path: "/assets/structures/medieval/overhang-round-railing.glb", category: "structures", subcategory: "roofs", description: "Rounded overhang with railing" },
      { name: "Pulley", path: "/assets/structures/medieval/pulley.glb", category: "props", subcategory: "interactive", description: "Rope and pulley mechanism" },
      { name: "Pulley Crate", path: "/assets/structures/medieval/pulley-crate.glb", category: "props", subcategory: "interactive", description: "Pulley with attached crate" },
      { name: "Roof", path: "/assets/structures/medieval/roof.glb", category: "structures", subcategory: "roofs", description: "Standard roof section" },
      { name: "Roof Corner", path: "/assets/structures/medieval/roof-corner.glb", category: "structures", subcategory: "roofs", description: "Roof corner piece" },
      { name: "Roof Edge", path: "/assets/structures/medieval/roof-edge.glb", category: "structures", subcategory: "roofs", description: "Roof edge trim piece" },
      { name: "Roof High Side", path: "/assets/structures/medieval/roof-high-side.glb", category: "structures", subcategory: "roofs", description: "High-pitched roof side section" },
      { name: "Roof High Side Corner", path: "/assets/structures/medieval/roof-high-side-corner.glb", category: "structures", subcategory: "roofs", description: "High roof side corner piece" },
      { name: "Roof High Side Corner Inner", path: "/assets/structures/medieval/roof-high-side-corner-inner.glb", category: "structures", subcategory: "roofs", description: "High roof inner corner piece" },
      { name: "Roof Side", path: "/assets/structures/medieval/roof-side.glb", category: "structures", subcategory: "roofs", description: "Roof side section" },
      { name: "Roof Side Corner", path: "/assets/structures/medieval/roof-side-corner.glb", category: "structures", subcategory: "roofs", description: "Roof side corner piece" },
      { name: "Roof Side Corner Inner", path: "/assets/structures/medieval/roof-side-corner-inner.glb", category: "structures", subcategory: "roofs", description: "Roof side inner corner piece" },
      { name: "Stairs Corner", path: "/assets/structures/medieval/stairs-corner.glb", category: "structures", subcategory: "traversal", description: "Corner staircase section" },
      { name: "Stairs Stone", path: "/assets/structures/medieval/stairs-stone.glb", category: "structures", subcategory: "traversal", description: "Stone staircase" },
      { name: "Stairs Wood", path: "/assets/structures/medieval/stairs-wood.glb", category: "structures", subcategory: "traversal", description: "Wooden staircase" },
      { name: "Structure", path: "/assets/structures/medieval/structure.glb", category: "structures", subcategory: "framework", description: "Basic structural framework" },
      { name: "Structure Cross", path: "/assets/structures/medieval/structure-cross.glb", category: "structures", subcategory: "framework", description: "Cross-braced structural frame" },
      { name: "Structure Pole", path: "/assets/structures/medieval/structure-pole.glb", category: "structures", subcategory: "framework", description: "Single structural pole" },
      { name: "Structure Poles", path: "/assets/structures/medieval/structure-poles.glb", category: "structures", subcategory: "framework", description: "Multiple structural poles" },
      { name: "Structure Wall", path: "/assets/structures/medieval/structure-wall.glb", category: "structures", subcategory: "framework", description: "Structural wall frame" },
      { name: "Structure Wall Cross", path: "/assets/structures/medieval/structure-wall-cross.glb", category: "structures", subcategory: "framework", description: "Cross-braced wall frame" },
      { name: "Tower", path: "/assets/structures/medieval/tower.glb", category: "structures", subcategory: "towers", description: "Medieval stone tower" },
      { name: "Tower Base", path: "/assets/structures/medieval/tower-base.glb", category: "structures", subcategory: "towers", description: "Tower base foundation" },
      { name: "Tower Edge", path: "/assets/structures/medieval/tower-edge.glb", category: "structures", subcategory: "towers", description: "Tower edge connector piece" },
      { name: "Tower Paint", path: "/assets/structures/medieval/tower-paint.glb", category: "structures", subcategory: "towers", description: "Painted stone tower" },
      { name: "Tower Paint Base", path: "/assets/structures/medieval/tower-paint-base.glb", category: "structures", subcategory: "towers", description: "Painted tower base" },
      { name: "Tower Top", path: "/assets/structures/medieval/tower-top.glb", category: "structures", subcategory: "towers", description: "Tower top cap piece" },
      { name: "Tree Large", path: "/assets/structures/medieval/tree-large.glb", category: "props", subcategory: "nature", description: "Large medieval-style tree" },
      { name: "Tree Shrub", path: "/assets/structures/medieval/tree-shrub.glb", category: "props", subcategory: "nature", description: "Small shrub bush" },
      { name: "Wall", path: "/assets/structures/medieval/wall.glb", category: "structures", subcategory: "walls", description: "Standard medieval stone wall" },
      { name: "Wall Detail", path: "/assets/structures/medieval/wall-detail.glb", category: "structures", subcategory: "walls", description: "Detailed stone wall section" },
      { name: "Wall Door", path: "/assets/structures/medieval/wall-door.glb", category: "structures", subcategory: "walls", description: "Stone wall with door opening" },
      { name: "Wall Flat Gate", path: "/assets/structures/medieval/wall-flat-gate.glb", category: "structures", subcategory: "walls", description: "Flat wall with gate opening" },
      { name: "Wall Fortified", path: "/assets/structures/medieval/wall-fortified.glb", category: "structures", subcategory: "walls", description: "Fortified castle wall" },
      { name: "Wall Fortified Door", path: "/assets/structures/medieval/wall-fortified-door.glb", category: "structures", subcategory: "walls", description: "Fortified wall with door" },
      { name: "Wall Fortified Gate", path: "/assets/structures/medieval/wall-fortified-gate.glb", category: "structures", subcategory: "walls", description: "Fortified wall with gate" },
      { name: "Wall Fortified Gate Half", path: "/assets/structures/medieval/wall-fortified-gate-half.glb", category: "structures", subcategory: "walls", description: "Half fortified gate wall" },
      { name: "Wall Fortified Half", path: "/assets/structures/medieval/wall-fortified-half.glb", category: "structures", subcategory: "walls", description: "Half-length fortified wall" },
      { name: "Wall Fortified Paint", path: "/assets/structures/medieval/wall-fortified-paint.glb", category: "structures", subcategory: "walls", description: "Painted fortified wall" },
      { name: "Wall Fortified Paint Door", path: "/assets/structures/medieval/wall-fortified-paint-door.glb", category: "structures", subcategory: "walls", description: "Painted fortified wall with door" },
      { name: "Wall Fortified Paint Gate", path: "/assets/structures/medieval/wall-fortified-paint-gate.glb", category: "structures", subcategory: "walls", description: "Painted fortified wall with gate" },
      { name: "Wall Fortified Paint Half", path: "/assets/structures/medieval/wall-fortified-paint-half.glb", category: "structures", subcategory: "walls", description: "Half painted fortified wall" },
      { name: "Wall Fortified Paint Window", path: "/assets/structures/medieval/wall-fortified-paint-window.glb", category: "structures", subcategory: "walls", description: "Painted fortified wall with window" },
      { name: "Wall Fortified Window", path: "/assets/structures/medieval/wall-fortified-window.glb", category: "structures", subcategory: "walls", description: "Fortified wall with window" },
      { name: "Wall Gate", path: "/assets/structures/medieval/wall-gate.glb", category: "structures", subcategory: "walls", description: "Stone wall with gate" },
      { name: "Wall Gate Half", path: "/assets/structures/medieval/wall-gate-half.glb", category: "structures", subcategory: "walls", description: "Half wall with gate" },
      { name: "Wall Half", path: "/assets/structures/medieval/wall-half.glb", category: "structures", subcategory: "walls", description: "Half-length stone wall" },
      { name: "Wall Low", path: "/assets/structures/medieval/wall-low.glb", category: "structures", subcategory: "walls", description: "Low height stone wall" },
      { name: "Wall Paint", path: "/assets/structures/medieval/wall-paint.glb", category: "structures", subcategory: "walls", description: "Painted stone wall" },
      { name: "Wall Paint Detail", path: "/assets/structures/medieval/wall-paint-detail.glb", category: "structures", subcategory: "walls", description: "Painted wall with details" },
      { name: "Wall Paint Door", path: "/assets/structures/medieval/wall-paint-door.glb", category: "structures", subcategory: "walls", description: "Painted wall with door" },
      { name: "Wall Paint Flat", path: "/assets/structures/medieval/wall-paint-flat.glb", category: "structures", subcategory: "walls", description: "Flat painted wall section" },
      { name: "Wall Paint Gate", path: "/assets/structures/medieval/wall-paint-gate.glb", category: "structures", subcategory: "walls", description: "Painted wall with gate" },
      { name: "Wall Paint Half", path: "/assets/structures/medieval/wall-paint-half.glb", category: "structures", subcategory: "walls", description: "Half painted wall" },
      { name: "Wall Paint Window", path: "/assets/structures/medieval/wall-paint-window.glb", category: "structures", subcategory: "walls", description: "Painted wall with window" },
      { name: "Wall Pane", path: "/assets/structures/medieval/wall-pane.glb", category: "structures", subcategory: "walls", description: "Wall with panel section" },
      { name: "Wall Pane Door", path: "/assets/structures/medieval/wall-pane-door.glb", category: "structures", subcategory: "walls", description: "Panel wall with door" },
      { name: "Wall Pane Paint", path: "/assets/structures/medieval/wall-pane-paint.glb", category: "structures", subcategory: "walls", description: "Painted panel wall" },
      { name: "Wall Pane Paint Door", path: "/assets/structures/medieval/wall-pane-paint-door.glb", category: "structures", subcategory: "walls", description: "Painted panel wall with door" },
      { name: "Wall Pane Painted Wood", path: "/assets/structures/medieval/wall-pane-painted-wood.glb", category: "structures", subcategory: "walls", description: "Painted wood panel wall" },
      { name: "Wall Pane Painted Wood Door", path: "/assets/structures/medieval/wall-pane-painted-wood-door.glb", category: "structures", subcategory: "walls", description: "Painted wood panel wall with door" },
      { name: "Wall Pane Painted Wood Window", path: "/assets/structures/medieval/wall-pane-painted-wood-window.glb", category: "structures", subcategory: "walls", description: "Painted wood panel wall with window" },
      { name: "Wall Pane Paint Window", path: "/assets/structures/medieval/wall-pane-paint-window.glb", category: "structures", subcategory: "walls", description: "Painted panel wall with window" },
      { name: "Wall Pane Window", path: "/assets/structures/medieval/wall-pane-window.glb", category: "structures", subcategory: "walls", description: "Panel wall with window" },
      { name: "Wall Pane Wood", path: "/assets/structures/medieval/wall-pane-wood.glb", category: "structures", subcategory: "walls", description: "Wood panel wall" },
      { name: "Wall Pane Wood Door", path: "/assets/structures/medieval/wall-pane-wood-door.glb", category: "structures", subcategory: "walls", description: "Wood panel wall with door" },
      { name: "Wall Pane Wood Window", path: "/assets/structures/medieval/wall-pane-wood-window.glb", category: "structures", subcategory: "walls", description: "Wood panel wall with window" },
      { name: "Wall Window", path: "/assets/structures/medieval/wall-window.glb", category: "structures", subcategory: "walls", description: "Stone wall with window" },
      { name: "Water", path: "/assets/structures/medieval/water.glb", category: "props", subcategory: "nature", description: "Water surface tile" },
      { name: "Wood Floor", path: "/assets/structures/medieval/wood-floor.glb", category: "structures", subcategory: "floors", description: "Wooden floor section" },
      { name: "Wood Floor Half", path: "/assets/structures/medieval/wood-floor-half.glb", category: "structures", subcategory: "floors", description: "Half wooden floor section" },
      { name: "Wood Floor Quarter", path: "/assets/structures/medieval/wood-floor-quarter.glb", category: "structures", subcategory: "floors", description: "Quarter wooden floor section" },
      { name: "Wood Floor Railing", path: "/assets/structures/medieval/wood-floor-railing.glb", category: "structures", subcategory: "floors", description: "Wooden floor with railing" }
    ]
  },
  {
    name: "Kenney Dungeon Kit",
    path: "/assets/kenney-dungeon",
    description: "37 modular dungeon pieces including corridors, rooms, gates, stairs, and wall/floor templates",
    assets: [
      { name: "Corridor", path: "/assets/structures/dungeon/corridor.glb", category: "structures", subcategory: "corridors", description: "Standard dungeon corridor" },
      { name: "Corridor Corner", path: "/assets/structures/dungeon/corridor-corner.glb", category: "structures", subcategory: "corridors", description: "Corner corridor piece" },
      { name: "Corridor End", path: "/assets/structures/dungeon/corridor-end.glb", category: "structures", subcategory: "corridors", description: "Dead-end corridor piece" },
      { name: "Corridor Intersection", path: "/assets/structures/dungeon/corridor-intersection.glb", category: "structures", subcategory: "corridors", description: "Four-way corridor intersection" },
      { name: "Corridor Junction", path: "/assets/structures/dungeon/corridor-junction.glb", category: "structures", subcategory: "corridors", description: "T-junction corridor piece" },
      { name: "Corridor Transition", path: "/assets/structures/dungeon/corridor-transition.glb", category: "structures", subcategory: "corridors", description: "Corridor width transition piece" },
      { name: "Corridor Wide", path: "/assets/structures/dungeon/corridor-wide.glb", category: "structures", subcategory: "corridors", description: "Wide dungeon corridor" },
      { name: "Corridor Wide Corner", path: "/assets/structures/dungeon/corridor-wide-corner.glb", category: "structures", subcategory: "corridors", description: "Wide corner corridor piece" },
      { name: "Corridor Wide End", path: "/assets/structures/dungeon/corridor-wide-end.glb", category: "structures", subcategory: "corridors", description: "Wide dead-end corridor" },
      { name: "Corridor Wide Intersection", path: "/assets/structures/dungeon/corridor-wide-intersection.glb", category: "structures", subcategory: "corridors", description: "Wide four-way intersection" },
      { name: "Corridor Wide Junction", path: "/assets/structures/dungeon/corridor-wide-junction.glb", category: "structures", subcategory: "corridors", description: "Wide T-junction corridor" },
      { name: "Gate", path: "/assets/structures/dungeon/gate.glb", category: "structures", subcategory: "doors", description: "Dungeon gate entrance" },
      { name: "Gate Door", path: "/assets/structures/dungeon/gate-door.glb", category: "structures", subcategory: "doors", description: "Gate with door" },
      { name: "Gate Door Window", path: "/assets/structures/dungeon/gate-door-window.glb", category: "structures", subcategory: "doors", description: "Gate with door and window" },
      { name: "Room Corner", path: "/assets/structures/dungeon/room-corner.glb", category: "structures", subcategory: "rooms", description: "Room corner piece" },
      { name: "Room Large", path: "/assets/structures/dungeon/room-large.glb", category: "structures", subcategory: "rooms", description: "Large dungeon room" },
      { name: "Room Large Variation", path: "/assets/structures/dungeon/room-large-variation.glb", category: "structures", subcategory: "rooms", description: "Large room alternate layout" },
      { name: "Room Small", path: "/assets/structures/dungeon/room-small.glb", category: "structures", subcategory: "rooms", description: "Small dungeon room" },
      { name: "Room Small Variation", path: "/assets/structures/dungeon/room-small-variation.glb", category: "structures", subcategory: "rooms", description: "Small room alternate layout" },
      { name: "Room Wide", path: "/assets/structures/dungeon/room-wide.glb", category: "structures", subcategory: "rooms", description: "Wide dungeon room" },
      { name: "Room Wide Variation", path: "/assets/structures/dungeon/room-wide-variation.glb", category: "structures", subcategory: "rooms", description: "Wide room alternate layout" },
      { name: "Stairs", path: "/assets/structures/dungeon/stairs.glb", category: "structures", subcategory: "traversal", description: "Dungeon staircase" },
      { name: "Stairs Wide", path: "/assets/structures/dungeon/stairs-wide.glb", category: "structures", subcategory: "traversal", description: "Wide dungeon staircase" },
      { name: "Template Corner", path: "/assets/structures/dungeon/template-corner.glb", category: "structures", subcategory: "templates", description: "Wall corner template piece" },
      { name: "Template Detail", path: "/assets/structures/dungeon/template-detail.glb", category: "structures", subcategory: "templates", description: "Detail decoration template" },
      { name: "Template Floor", path: "/assets/structures/dungeon/template-floor.glb", category: "structures", subcategory: "templates", description: "Standard floor template tile" },
      { name: "Template Floor Big", path: "/assets/structures/dungeon/template-floor-big.glb", category: "structures", subcategory: "templates", description: "Large floor template tile" },
      { name: "Template Floor Detail", path: "/assets/structures/dungeon/template-floor-detail.glb", category: "structures", subcategory: "templates", description: "Detailed floor template tile" },
      { name: "Template Floor Detail A", path: "/assets/structures/dungeon/template-floor-detail-a.glb", category: "structures", subcategory: "templates", description: "Floor detail variant A" },
      { name: "Template Floor Layer", path: "/assets/structures/dungeon/template-floor-layer.glb", category: "structures", subcategory: "templates", description: "Floor layer template" },
      { name: "Template Floor Layer Raised", path: "/assets/structures/dungeon/template-floor-layer-raised.glb", category: "structures", subcategory: "templates", description: "Raised floor layer template" },
      { name: "Template Wall", path: "/assets/structures/dungeon/template-wall.glb", category: "structures", subcategory: "templates", description: "Standard wall template" },
      { name: "Template Wall Corner", path: "/assets/structures/dungeon/template-wall-corner.glb", category: "structures", subcategory: "templates", description: "Wall corner template" },
      { name: "Template Wall Detail A", path: "/assets/structures/dungeon/template-wall-detail-a.glb", category: "structures", subcategory: "templates", description: "Wall detail variant A" },
      { name: "Template Wall Half", path: "/assets/structures/dungeon/template-wall-half.glb", category: "structures", subcategory: "templates", description: "Half-height wall template" },
      { name: "Template Wall Stairs", path: "/assets/structures/dungeon/template-wall-stairs.glb", category: "structures", subcategory: "templates", description: "Wall template with stairs cutout" },
      { name: "Template Wall Top", path: "/assets/structures/dungeon/template-wall-top.glb", category: "structures", subcategory: "templates", description: "Wall top cap template" }
    ]
  }
];

export function getAssetsByCategory(category: string): AssetInfo[] {
  return ASSET_CATALOG.flatMap(pack => pack.assets.filter(a => a.category === category));
}

export function getAssetsBySubcategory(subcategory: string): AssetInfo[] {
  return ASSET_CATALOG.flatMap(pack => pack.assets.filter(a => a.subcategory === subcategory));
}

export function searchAssets(query: string): AssetInfo[] {
  const lowerQuery = query.toLowerCase();
  return ASSET_CATALOG.flatMap(pack => 
    pack.assets.filter(a => 
      a.name.toLowerCase().includes(lowerQuery) ||
      a.category.toLowerCase().includes(lowerQuery) ||
      a.subcategory?.toLowerCase().includes(lowerQuery) ||
      a.description?.toLowerCase().includes(lowerQuery)
    )
  );
}

export function getAnimatedAssets(): AssetInfo[] {
  return ASSET_CATALOG.flatMap(pack => pack.assets.filter(a => a.animations && a.animations.length > 0));
}

export function getAllAssetPaths(): string[] {
  return ASSET_CATALOG.flatMap(pack => pack.assets.map(a => a.path));
}
